import os
Import('env', 'useAudio')

headers = Split("""
	AgentVisualDebugger.h
	AudioManager.h
	Car.h
	DataCollection.h
	DataFile.h
	LearningEntity.h
	LearningTest.h
	PhysicalCamera.h
	PhysicalEntity.h
	Robot.h
	SimulationEngine.h
	SimulationFrameListener.h
	Timer.h
""")

sources = Split("""
	AgentVisualDebugger.cpp
	Car.cpp
	DataCollection.cpp
	DataFile.cpp
	LearningTest.cpp
	PhysicalCamera.cpp
	PhysicalEntity.cpp
	Robot.cpp
	SimulationEngine.cpp
	Timer.cpp
""")

if useAudio == True:
	sources += Split("""
		AudioManager.cpp
		""")

objects = env.SharedObject(sources)

# Add header installation to 'install' alias
env.Alias('install', env.Install(os.path.join(env['prefix'], 'include/verve/apps'), headers))

temp = ''
Return('objects')

