{'application':{'type':'Application',
          'name':'Minimal',
    'backgrounds': [
    {'type':'Background',
          'name':'bgMin',
          'title':'Minimal PythonCard Application',
          'size':(1191, 879),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuFile',
             'label':'&File',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuFileExit',
                   'label':'E&xit\tAlt+X',
                   'command':'exit',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Slider', 
    'name':'discountTCSlider', 
    'position':(10, 490), 
    'size':(140, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':50, 
    'ticks':True, 
    'value':0, 
    },

{'type':'Slider', 
    'name':'eTraceTCSlider', 
    'position':(10, 360), 
    'size':(140, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':50, 
    'ticks':True, 
    'value':0, 
    },

{'type':'StaticText', 
    'name':'discountTCText', 
    'position':(10, 470), 
    'text':'Discount Rate Time Constant', 
    },

{'type':'StaticText', 
    'name':'eTraceTCText', 
    'position':(10, 340), 
    'text':'Eligibility Trace Time Constant', 
    },

{'type':'TextField', 
    'name':'discountTCTextField', 
    'position':(80, 430), 
    'size':(72, 36), 
    'alignment':'right', 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'TextField', 
    'name':'eTraceTCTextField', 
    'position':(80, 300), 
    'size':(72, 36), 
    'alignment':'right', 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'StaticText', 
    'name':'learningRateText', 
    'position':(10, 200), 
    'text':'Learning Rate', 
    },

{'type':'Slider', 
    'name':'learningRateSlider', 
    'position':(10, 220), 
    'size':(140, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':0, 
    'tickFrequency':50, 
    'ticks':True, 
    'value':0, 
    },

{'type':'TextField', 
    'name':'learningRateTextField', 
    'position':(80, 180), 
    'size':(72, 36), 
    'alignment':'right', 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'StaticText', 
    'name':'updateTimeText', 
    'position':(10, 640), 
    'text':'Update Duration (seconds)', 
    },

{'type':'TextField', 
    'name':'updateTimeTextField', 
    'position':(80, 600), 
    'size':(72, 36), 
    'alignment':'right', 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'StaticText', 
    'name':'plot4Text', 
    'position':(240, 700), 
    'text':'TD Error', 
    },

{'type':'TextField', 
    'name':'tdErrorTextField', 
    'position':(290, 680), 
    'size':(72, 36), 
    'alignment':'right', 
    'backgroundColor':(255, 0, 0), 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'TextField', 
    'name':'valEstTextField', 
    'position':(290, 490), 
    'size':(72, 36), 
    'alignment':'right', 
    'backgroundColor':(0, 255, 0), 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'StaticText', 
    'name':'plot3Text', 
    'position':(200, 510), 
    'text':'Value Estimation', 
    },

{'type':'TextField', 
    'name':'rewardTextField', 
    'position':(290, 300), 
    'size':(72, 36), 
    'alignment':'right', 
    'backgroundColor':(0, 0, 255), 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'TextField', 
    'name':'inputTextField', 
    'position':(290, 90), 
    'size':(72, 36), 
    'alignment':'right', 
    'backgroundColor':(128, 128, 128), 
    'editable':False, 
    'font':{'faceName': 'Tahoma', 'family': 'sansSerif', 'size': 16}, 
    'text':'0.0', 
    },

{'type':'Slider', 
    'name':'rewardSlider', 
    'position':(210, 340), 
    'size':(140, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':-100, 
    'tickFrequency':50, 
    'ticks':True, 
    'value':0, 
    },

{'type':'Slider', 
    'name':'inputSlider', 
    'position':(210, 130), 
    'size':(140, -1), 
    'labels':False, 
    'layout':'horizontal', 
    'max':100, 
    'min':-100, 
    'tickFrequency':50, 
    'ticks':True, 
    'value':0, 
    },

{'type':'StaticText', 
    'name':'rewardStaticText', 
    'position':(240, 320), 
    'text':'Reward', 
    },

{'type':'StaticText', 
    'name':'inputStaticText', 
    'position':(210, 110), 
    'text':'Sensory Input', 
    },

{'type':'BitmapCanvas', 
    'name':'canvas', 
    'position':(370, 10), 
    'size':(800, 800), 
    'backgroundColor':(255, 255, 255), 
    'font':{'faceName': 'Arial', 'family': 'sansSerif', 'size': 8}, 
    },

{'type':'Button', 
    'name':'updateButton', 
    'position':(50, 680), 
    'size':(96, 41), 
    'label':'Update', 
    },

] # end components
} # end background
] # end backgrounds
} }
