import os
import glob

Import('env')
headers = glob.glob('*.h')
sources = glob.glob('*.cpp')
objects = env.SharedObject(sources)

# Add header installation to 'install' alias.
env.Alias('install', env.Install(os.path.join(env['prefix'], 'include/opal'), headers))

Return('objects')
