import os

sources = Split("""
	main.cpp
""")

# Setup options
opts = Options()
opts.AddOptions(
	PathOption('extra_include_path', 'Additional include directory', '.'), 
	PathOption('extra_lib_path', 'Additional lib directory', '.')
)

env = Environment(
	ENV = os.environ,
	options = opts
)

if env['PLATFORM'] == 'win32':
	env.Append(CXXFLAGS = ['/EHsc', '/wd4996'], 
		CPPDEFINES = ['/DNDEBUG'])

env.Help(opts.GenerateHelpText(env))

env.Append(CPPPATH = env['extra_include_path'], 
	LIBPATH = env['extra_lib_path'])

env.Append(LIBS = ['corona'])

env.Program('verveVIC', sources)
